WHISPER_CPP_VERSION = v1.7.2
WHISPER_CPP_SITE = $(call github,ggerganov,whisper.cpp,$(WHISPER_CPP_VERSION))
WHISPER_CPP_LICENSE = MIT
WHISPER_CPP_INSTALL_STAGING = NO
WHISPER_CPP_INSTALL_TARGET = YES

WHISPER_CPP_CONF_OPTS = \
	-DGGML_CUDA=OFF \
	-DGGML_METAL=OFF \
	-DBUILD_SHARED_LIBS=OFF

define WHISPER_CPP_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/bin/main $(TARGET_DIR)/usr/bin/whisper-cli
endef

$(eval $(cmake-package))
